export const CHANGE_DIFFICULTY_PAGE = "change_difficulty";
export const GAME_PAGE = "game";
export const pathToCard = "./static/img";
export const cards = [
   `${pathToCard}/туз пики.png`,
   `${pathToCard}/король пики.png`,
   `${pathToCard}/валет пики.png`,
   `${pathToCard}/дама пики.png`,
   `${pathToCard}/10 пики.png`,
   `${pathToCard}/9 пики.png`,
   `${pathToCard}/8 пики.png`,
   `${pathToCard}/7 пики.png`,
   `${pathToCard}/6 пики.png`,
   `${pathToCard}/туз черви.png`,
   `${pathToCard}/король черви.png`,
   `${pathToCard}/валет черви.png`,
   `${pathToCard}/дама черви.png`,
   `${pathToCard}/10 черви.png`,
   `${pathToCard}/9 черви.png`,
   `${pathToCard}/8 черви.png`,
   `${pathToCard}/7 черви.png`,
   `${pathToCard}/6 черви.png`,
   `${pathToCard}/туз крести.png`,
   `${pathToCard}/король крести.png`,
   `${pathToCard}/валет крести.png`,
   `${pathToCard}/дама крести.png`,
   `${pathToCard}/10 крести.png`,
   `${pathToCard}/9 крести.png`,
   `${pathToCard}/8 крести.png`,
   `${pathToCard}/7 крести.png`,
   `${pathToCard}/6 крести.png`,
   `${pathToCard}/туз бубны.png`,
   `${pathToCard}/король бубны.png`,
   `${pathToCard}/валет бубны.png`,
   `${pathToCard}/дама бубны.png`,
   `${pathToCard}/10 бубны.png`,
   `${pathToCard}/9 бубны.png`,
   `${pathToCard}/8 бубны.png`,
   `${pathToCard}/7 бубны.png`,
   `${pathToCard}/6 бубны.png`,
];
