export const CHANGE_DIFFICULTY_PAGE = "change_difficulty";
export const GAME_PAGE = "game";
export const cards = [
   '<img src="./src/img/туз пики.png" alt="">',
   '<img src="./src/img/король пики.png" alt="">',
   '<img src="./src/img/валет пики.png" alt="">',
   '<img src="./src/img/дама пики.png" alt="">',
   '<img src="./src/img/10 пики.png" alt="">',
   '<img src="./src/img/9 пики.png" alt="">',
   '<img src="./src/img/8 пики.png" alt="">',
   '<img src="./src/img/7 пики.png" alt="">',
   '<img src="./src/img/6 пики.png" alt="">',
   '<img src="./src/img/туз черви.png" alt="">',
   '<img src="./src/img/король черви.png" alt="">',
   '<img src="./src/img/валет черви.png" alt="">',
   '<img src="./src/img/дама черви.png" alt="">',
   '<img src="./src/img/10 черви.png" alt="">',
   '<img src="./src/img/9 черви.png" alt="">',
   '<img src="./src/img/8 черви.png" alt="">',
   '<img src="./src/img/7 черви.png" alt="">',
   '<img src="./src/img/6 черви.png" alt="">',
   '<img src="./src/img/туз крести.png" alt="">',
   '<img src="./src/img/король крести.png" alt="">',
   '<img src="./src/img/валет крести.png" alt="">',
   '<img src="./src/img/дама крести.png" alt="">',
   '<img src="./src/img/10 крести.png" alt="">',
   '<img src="./src/img/9 крести.png" alt="">',
   '<img src="./src/img/8 крести.png" alt="">',
   '<img src="./src/img/7 крести.png" alt="">',
   '<img src="./src/img/6 крести.png" alt="">',
   '<img src="./src/img/туз бубны.png" alt="">',
   '<img src="./src/img/король бубны.png" alt="">',
   '<img src="./src/img/валет бубны.png" alt="">',
   '<img src="./src/img/дама бубны.png" alt="">',
   '<img src="./src/img/10 бубны.png" alt="">',
   '<img src="./src/img/9 бубны.png" alt="">',
   '<img src="./src/img/8 бубны.png" alt="">',
   '<img src="./src/img/7 бубны.png" alt="">',
   '<img src="./src/img/6 бубны.png" alt="">',
];
